[package]
name = "motor_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "motor_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
p256 = { version = "0.13", features = ["ecdsa", "pkcs8"] }
rand_core = { version = "0.6", features = ["std"] }
hex = "0.4"
